---
title: "RAPID Alpha Diversity Group Significance"
author: "Becca Maher"
date: "6/6/2019"
output: html_document
---
## Script for calculating alpha diversity statistics and testing for significant differences with metadata variables

### 1 Setup the working space
```{r libraries, include=FALSE}
rm(list=ls())
library(phyloseq)
library(multcomp)
library(picante)
library(ggplot2 )
library(tidyverse)
library(FSA)
library(MASS)
library(lme4)
library(lmerTest)
library(emmeans)
library(MuMIn)
library(nlme)
```

#### Functions
```{r functions}
# Arc-sine transformation
asinTransform <- function(p) { asin(sqrt(p)) }
# Calculate standard error
sderr <- function(x) {sd(x)/sqrt(length(x))}
#+++++++++++++++++++++++++
# Function to calculate the mean and the standard deviation
# for each group
#+++++++++++++++++++++++++
# data : a data frame
# varname : the name of a column containing the variable
#to be summariezed
# groupnames : vector of column names to be used as
# grouping variables
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sderr(x[[col]]), na.rm=TRUE)
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}

# function to visualize the boxplot, histogram, QQ-plot, and kernel density estimate plot for residuals
normality.plots <- function(x) {
  par(mfrow=c(2,2))
  hist(residuals(x), main = "Histogram", xlab = "Values")
  boxplot(residuals(x), main = "Boxplot", ylab = "Values")
  qqnorm(residuals(x))
  qqline(residuals(x))
  plot(density(residuals(x)), main = "Kernel Density Estimate")
}

# function to visaulize the fitted vs. residuals of model and the absolute residuals vs. fitted
var.plots <- function(x) {
  par(mfrow=c(1,2))
  plot(x = fitted(x), y = residuals(x), xlab="Fitted", ylab="Residuals")
  abline(h=0)
  title("Residuals vs. Fitted")
  plot(x = fitted(x), y = abs(residuals(x)), xlab="Fitted", ylab="Absolute Residuals")
  abline(h=0)
  title("Absolute Residuals vs. Fitted")
}
```

#### Load the data
Load the alphadiv.csv files created in the RAPID_alpha_statsA.Rmd script. First starting with all species
```{r load}
alphadiv <- read.csv("~/Box Sync/RAPID/RAPID-analysis/data/alphadiv.csv")
str(alphadiv)
```


### 2 Data Exploration
#### Data summaries
```{r}
# Data summaries
data_summary(alphadiv, varname = "richness", groupnames = c("treatment"))
data_summary(alphadiv, varname = "richness", groupnames = c("time"))
data_summary(alphadiv, varname = "richness", groupnames = c("species"))
data_summary(alphadiv, varname = "richness", groupnames = c("species", "time"))

data_summary(alphadiv, varname = "evenness", groupnames = c("treatment"))
data_summary(alphadiv, varname = "evenness", groupnames = c("time"))
data_summary(alphadiv, varname = "evenness", groupnames = c("species"))
data_summary(alphadiv, varname = "evenness", groupnames = c("species", "time"))

data_summary(alphadiv, varname = "faithPD", groupnames = c("treatment"))
data_summary(alphadiv, varname = "faithPD", groupnames = c("time"))
data_summary(alphadiv, varname = "faithPD", groupnames = c("species"))
data_summary(alphadiv, varname = "faithPD", groupnames = c("species", "time"))
```

### 3 Analysis with linear-mixed effects models

```{r}
# Chao1 Index
# include random effect
lmerR <- lmer(sqrt(richness)~ time*treatment*species + (1|indiv), data = alphadiv)

anova(lmerR)
summary(lmerR)
var.plots(lmerR)
normality.plots(lmerR)

# post hoc tests for time by species
lmerR1 <- lmer(sqrt(richness)~ time * species + (1|indiv), data = alphadiv)
anova(lmerR1)

emmeans(lmerR1, list(pairwise ~ time * species), adjust = "tukey")

# within species models
alphadiv_acr <- alphadiv[which(alphadiv$species == "ACR"),]
lmerA <- lmer(sqrt(richness) ~ time + (1|indiv), data = alphadiv_acr)
anova(lmerA)
emmeans(lmerA, list(pairwise ~ time), adjust = "tukey")

alphadiv_poc <- alphadiv[which(alphadiv$species == "POC"),]
lmerP <- lmer(sqrt(richness) ~ time + (1|indiv), data = alphadiv_poc)
anova(lmerP)
emmeans(lmerP, list(pairwise ~ time), adjust = "tukey")

alphadiv_por <- alphadiv[which(alphadiv$species == "POR"),]
lmerR <- lmer(sqrt(richness) ~ time + (1|indiv), data = alphadiv_por)
anova(lmerR)
emmeans(lmerR, list(pairwise ~ time), adjust = "tukey")

```

```{r}
# Simpson's Index
lmerR <- lmer(asinTransform(evenness)~ time*treatment*species + (1|indiv), data = alphadiv)
anova(lmerR)
summary(lmerR) # random effect variance explains .06

var.plots(lmerR)
normality.plots(lmerR)

# post hoc tests for main effects
lmerR1 <- lmer(asinTransform(evenness) ~ time*species + (1|indiv), data = alphadiv)
anova(lmerR1)

emmeans(lmerR1, list(pairwise ~ time), adjust = "tukey")

# within species models
lmerA <- lmer(asinTransform(evenness) ~ time + (1|indiv), data = alphadiv_acr)
anova(lmerA)
emmeans(lmerA, list(pairwise ~ time), adjust = "tukey")

lmerP <- lmer(asinTransform(evenness) ~ time + (1|indiv), data = alphadiv_poc)
anova(lmerP)
emmeans(lmerP, list(pairwise ~ time), adjust = "tukey")

lmerR <- lmer(asinTransform(evenness) ~ time + (1|indiv), data = alphadiv_por)
anova(lmerR)
emmeans(lmerR, list(pairwise ~ time), adjust = "tukey")
```

```{r}
# Faith's PD
lmerR <- lmer(sqrt(faithPD)~ time*treatment*species + (1|indiv), data = alphadiv)
anova(lmerR)
summary(lmerR) # random effect variance explains .06

var.plots(lmerR)
normality.plots(lmerR)

# post hoc tests for main effects
lmerR1 <- lmer(sqrt(faithPD) ~ time * species + (1|indiv), data = alphadiv)
anova(lmerR1)

emmeans(lmerR1, list(pairwise ~ time), adjust = "tukey")

# within species models
lmerA <- lmer(sqrt(faithPD) ~ time + (1|indiv), data = alphadiv_acr)
anova(lmerA)
emmeans(lmerA, list(pairwise ~ time), adjust = "tukey")

lmerP <- lmer(sqrt(faithPD) ~ time + (1|indiv), data = alphadiv_poc)
anova(lmerP)
emmeans(lmerP, list(pairwise ~ time), adjust = "tukey")

lmerR <- lmer(sqrt(faithPD) ~ time + (1|indiv), data = alphadiv_por)
anova(lmerR)
emmeans(lmerR, list(pairwise ~ time), adjust = "tukey")
```